### PR TITLE
fix(sand-agent-cli): document `ip-range` flag

### PR DESCRIPTION
**Pull request by EtienneM**

### CODE REVIEW

**Comment by ipfaze** [comment]
Can you create an issue related to this PR and link it?

**Comment by EtienneM** [comment]
Why is that?

**Comment by ipfaze** [comment]
I was thinking about our ISMS rule: "one PR should be linked to an issue".
But it's not that well explain.
So forget my previous comment.

**Review by ipfaze — APPROVED** [review]
LGTM 👌

**Pull request merged**
